apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:46oR3Ply/VGcU3r0kc1TfG39O7on0Spbnu1cJjwVFulsS/D6,iv:npl/5NQ++K81xNIlTeTogpTR7bnOxQctLswmewmuotc=,tag:LZLkbDhDqiV4Mhm7TSdJQg==,type:str]
    credentials.json: ENC[AES256_GCM,data:tnh88fJIh8rv1TQL3bertyWw+MDhQ50tCcB5SFZAHNhDAmlLFDY4tOMk5Gd7tq0eWEyfg7QSV5aTVj6BVqC3o1XLJClBG9qHIeqghi4Zjc8p3rUAFDFGUPza5OObV6osNJ5z/3IfPwNbBWIsYdAjHL+8X/WFH878fExhsLzs/vE9unfakUIC8vblSuRPRQ0OHba16CCJBHLfDsdDbi9R5F+ldL9m5sp86ZgNI8EtTQ==,iv:nY2j8H56+non/s+K2FIvbJShbV6fAyE8SeNpHY+iQWc=,tag:z8QFT5suk697O+KdwHl5GA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q8aex20qchscezvgg0ppgcpv0j5mpw9tklr4vakztnktekzscp3q248v2s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnRjZKSW5UWTRsYk8wZGNW
            MUlQTXNWYXhyV0YvZlF1SjdkVXJVVVNmYXl3CnkxWm5QNEh4TWVqdjVRSFBBR3Ji
            NkZZQXNqd0U3dnUxMzAzZ2w0Tkl1YlkKLS0tIFFpVkJPL2o1WEphQng3TFpVQXpp
            T1BMUkR5eEJnV2ZMMGNRc1ZCNVY0L1EKLECKmD2YUG/v67caBE23zbk5338WNvYN
            kOwRbnn8s6BeADZHtwBghs/B0ibI5LW7PYzwIAgc7M/awcf+6G1tmQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-18T03:05:25Z"
    mac: ENC[AES256_GCM,data:zrUuo3NRpgd8Fw5i7+JAcjmWkk3sdPqbFeb9UztoskPZnGZQfhUUwrwYY1tGCvh2ce8j2bnZHgFKWC6oC7GmFVmS7veaqTBSYpZXxIdWIReu5+sKUwvUtbXTqorEmcISKACJeuU829Oox3VcSHwpYGEp8ZCH+6hLOzOgOF7kTTQ=,iv:w/VjFUULOA4behIAMt+1DRQlBD2eWaAqQ3afXJpWQuY=,tag:iLrxi1Nzu9N7OgRlHtsyAQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
