apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:UxoJ9sE/op4Ny/e4oof3unKfdccx85xEUQ26Yea5CleruOIZ,iv:Sluvi/U+C0Mheazdin1Zn9b99m4pJGW5pFYDImy9N/g=,tag:kFPOEQvO5cpzi3oYZ76oog==,type:str]
    credentials.json: ENC[AES256_GCM,data:C5L0AHd29vKuiJGWi4hH9Gmr4M1ZypwcIM7PbRzZHnYXoYA7qndQQ/TeWAVkJpO37LHdgtQS/SZSrh8XdVyXUlv7IDE6VZon1k52uB2vm4D1xyNe6OzA1mk+QJAdqb/p0X9pyulVx7hRWYFTAha3acJVqtAR2e0jbm9CXZqh60j5BJdWkswaVD1djwJoLT7Qh/dHCXQVYsMTpn5J/Omt5Rug/uaS3oZquXljNxm0WA==,iv:+UH1OUq8De+lHjxuXF2l1WJuhw+sNpTHqLLFhJx/Wk8=,tag:iUs6KxlqtE6hTRCVVndSiQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q8aex20qchscezvgg0ppgcpv0j5mpw9tklr4vakztnktekzscp3q248v2s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzZFVXV245Y3NKSnNiaGlD
            WlVHOGZ6aHBsU2MyQk5vb2dTRkJFVVY0N0E0CjlRREZRa2E2SS9GcWpaMDdMaEJ2
            dDZhaEJpci9LY3pHaGpLendiTXMzS00KLS0tIDJ4LzZtOTNwNkd0aWtVeWN2VWtE
            MVFoeVl6SlJOakVFaEQwL3E0TWVLMFkKislZXXJmrzZuPhQmE1oZ6TX3nakZaDFf
            dOj/iK4BcwByRckYYQUD1a1k+7lcBwITYPxS9vInfV4mcNDT0pzbjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-25T14:05:31Z"
    mac: ENC[AES256_GCM,data:FMITmcKgwRwf2RAMYnc0u+7lSpLLyPlLXbZMsL0oINJ13wQcnb+VwBTQexjYH4Qe4aZFWCvlb3df7gXuOP35vYqLQGk8alnxa8QaQqddtKU5zx+B7LeQfvlhDD5arhdtJIShJy8Y4gF4BAgtwuB0f6+u7GFRlsKnBIsUlE684To=,iv:ZLwfbxStEgcmgoNdZ7hawpGT/IRcckHH2XIEGzko7bM=,tag:hO8zfuC1LlbJIqgj0WlRaA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
