apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:CW7qIbkG4162SLSvXJtopHVwScnKTQImrwxD52AbmvTTkAF1,iv:etivBge5Si76flW5Q+1j71VeopY3f9bgIdUHlntF4MI=,tag:IufdA6gQNZ7S1V+6vSkavQ==,type:str]
    credentials.json: ENC[AES256_GCM,data:tRZP4PVphGG2S5QuaA+z+Iu+Gth7PbIPlrDcnfqmaQ61K1iv+KK7GwCqfn/qt4sZQW2c07alojkZhYW0MdaHyIgPkUrUquENsaadGLa1vvW7h0ideKLZZH4SlyPQ8ROz7hEETsMiZr3CLbft71r9bHrtXa/dRl9HPbmfOmG+l0o8d1HvBazUmTtgeVmM7mPjzG82+EqDsPiCYxVExqqukWYuj1g8BSS4sjKJ8X2D/Q==,iv:K0g2+ACGhUSwwmeG3h05t5J52ah+3bmgomxTm1P1Npg=,tag:D4KmpeqL7qnhxIbth7iFFA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q8aex20qchscezvgg0ppgcpv0j5mpw9tklr4vakztnktekzscp3q248v2s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIc01PQ0RCVWIwRTVEUldK
            WGlVQ0J1ZFBCU1h1cmNjcWJiVzRaUWI2VG5FCnQ2aU9oc0szOWNuSHFNS2M2RU1L
            TlBDRURFZE1FNW10NXpJczhHZHNVU0kKLS0tIFlTc0p4ZlVYYTlVLzU2NjQwYUg2
            eUNVVm9YbzRQaVpvRTJLVlVIMkRmdWcKzP89HQEvZ5ZAR+pOUZpFZNQkm7mq/7Zf
            phC6GsNxT5rmo6hO4rqtIKFUkQ0zBddhrQCZ/KnACPPNzHS3wuozmQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-26T17:18:57Z"
    mac: ENC[AES256_GCM,data:+eq3MA1Id0Y/zCk+xgkx3PQnL9WLTST5ZyLOGKXjRQBUTD6cOsR5dB1lVSOd6wMu5LMpwFkF7aMkXV5CuJSTl2hNFjb/cgN0cjiHFMuyRMJ8+8+zKntdMzyTRwZKvYiQsxdzDTGW280AIIzH4scTRbj8T5bm8rAuZScUX6wovDg=,iv:Gs9cz2shhlcUJ1rV3leot8q8GEtZAIMUbXfbXpKmUOc=,tag:6l4FqiQurbeUXs+9VBEBSQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
