---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app mariadb-operator
  namespace: flux-system
spec:
  targetNamespace: db-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apps/database-system/mariadb/operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false
  interval: 5m
  retryInterval: 1m
  timeout: 5m
