---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: piraeus
  namespace: flux-system
spec:
  interval: 2m0s
  path: ./config/default
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: piraeus
  targetNamespace: piraeus-system
  timeout: 3m0s
  wait: true