---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: Kustomization
metadata:
  name: piraeus
  namespace: flux-system
spec:
  interval: 30m0s
  path: ./kustomize
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: piraeus
  targetNamespace: piraeus-system
  timeout: 3m0s
  wait: true