---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mysql
spec:
  interval: 30m
  chart:
    spec:
      chart: mysql
      sourceRef:
        kind: OCIRepository
        name: mysql
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: mysql-helm-values
