---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx
spec:
  interval: 30m
  chart:
    spec:
      chart: nginx
      version: 1.27.1
      sourceRef:
        kind: OCIRepository
        name: nginx
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: nginx-helm-values
  values:
    ingress:
      app:
        className: internal
        hosts: ["{{ .Release.Name }}.${SECRET_DOMAIN}"]
