---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
configMapGenerator:
  - name: longhorn-helm-chart-value-overrides
    files:
      - values.yaml=./helm-values.yaml
configurations:
  - kustomizeconfig.yaml