apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:Vr7V9PX6jJG0ErIuuItfAIWD6m1nLOkWAiv6+dhDd/6ho5D+L9uMxw==,iv:3jivGbLeCEIdRxWvdgETIWRj0pw7DJVkbu224u0mlJU=,tag:98Tu0ubuPAHsA1OyI3dXLg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q8aex20qchscezvgg0ppgcpv0j5mpw9tklr4vakztnktekzscp3q248v2s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQWGJrUFRhcmlpRjBVMU5Y
            VWhJVWtYRElHbkdZNEdIOE1vREd6SDNwd2lvCnFIQUVmUkdxOFZtekNxTFVVZ05B
            Z3pqbnF4dFdIRkJFOUdlNUlMMGQ3d1kKLS0tIDNvYzBsVFloODdrT3JQaEUrU05J
            emhhTVlEVGxjekVxak4rQ1dCQ3hEQTQKzu2PvH1UAdBnVaDEdc7mK0t6P2i2krlQ
            BWfhwQU3AB6+SN4y5QUxZHyqfGusaVM8cGZr8NGJ3ISHC+pSGuqNqg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-25T22:52:09Z"
    mac: ENC[AES256_GCM,data:dRAe0DU+s8fyUHo2hOylwDjX2rbLc+ZRWlvHJQGBkBOUu3k5xTZ2zCizAgGLQKx4K2YxAGxuKN+hNn3foyKXTXuZnwW39hcEuGn9C/nOehL1is0rfgKy38DowZQ36vE4O3h4m1tnqSRj4bW5vsnwLKW1gJqBQh22d5SpQ8gwtSk=,iv:VDH45S3M7vrezO8XAVQ0wci5bE5Tgu8MAy5tl0rk4ss=,tag:Hx/06xPhQ1WzM12zHoPQgw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
