apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:TJsmsxeOzlkRiUREjYl6quIb7ftjz3pXrYyD0/UcwLyRC/w2SB41Zw==,iv:dKDyRXWexxz2gUnvwG43HZ9215uGhMYExScZl5KrsWc=,tag:cRqwHbYNUtEADOy26cZ2aA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q8aex20qchscezvgg0ppgcpv0j5mpw9tklr4vakztnktekzscp3q248v2s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzMXVId1lFaUhMNnB0Ykw3
            NGMxdTBjNW5wajhqTGFKa005TXFDbWZZZ0YwCmNaR3RJMk54dUhuT3BYMnRDenVW
            VWk1MEVNektTeDJsbFc3M2pJT3VyVzgKLS0tIGlFRExsRFM3NjNwVFMyRVczMEU0
            RnpEU0JWemc5dmFGeVZ2R1VHSmQ4a1kK7FlyTy3dGchW4fnB/+0e0/kXUeI0mnNM
            7SFu8mBHV+M2hVkju1uQpb+ezHJ2Escm2vQ8Qj+GuwzAEtE6jRorPg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-24T15:19:20Z"
    mac: ENC[AES256_GCM,data:SuX7MSSmbcPXOf8mWcBBHVn1q5RTGnK67MCa+12z/XmTJy/1LN21AjQu1/2tvRp/UahzY5bkeq8/91imoGGOGFYE7ZC7OXZi8WBlXS7yfvE0miTUGJuHJL/o3IxWbo5ky5wYLramE1qLYamumrLM+IwWehtnsOQPi2eb53K0et8=,iv:MDQXSoR6JHKlNiZ4C2c08dLO4uoThQ2ookhqzknRIaQ=,tag:l0USdblyPVTXC/iLlPWVKQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
