apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:7mbeNIm9uDJQWfvPl/86lP/dWe1lCLUO/YKYE2wFQRUVJqEAbw5ktQ==,iv:c92pg1RdQoAC7WMBt5t7nXKZKG5vYrGJHkZOC1kcYRs=,tag:m5WrYvefwuqp7j52XKFH4g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q8aex20qchscezvgg0ppgcpv0j5mpw9tklr4vakztnktekzscp3q248v2s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4a0RZb2J0MkJ2R0xFOU90
            MlAzZjRYZWV6dHJ1a3Q1bXlzaUdWZXZiSGhFClNyc2V3ekF0dlhNY1hJeXB3Zm1l
            cU5hZE5RSkFDaFFUa0JPK2Q1MzY1RG8KLS0tIFhiUHlvcWFnN2FGWmYvNWhqTW5q
            dmFTTTdpc0ZDRDhQYXJpaHpNbEphbVkKkbAbehUHbkFeUFmpgjY1mwdCVzVmjvBR
            l6SOPltJANorD7024ure6QkgXEkXIipw2Uq0XL4tv/2oQgTW6/7pZw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-18T06:13:32Z"
    mac: ENC[AES256_GCM,data:Mzrh/cLr7t96gmnje6U0avJdMIzmUeMGB/BYym1slPrSxiG6lpAc+EN+JuxQr0y5Oxz+4Aydp9sgT5QjqQxfR1dRbecdLDL5CUY5LyDLrC7Y8s91GNCYdhipeJpxIcqbF4UkJFnWLP+MqGyfkgGPLsmJ18D/ztaZ90ZCF1bP3hU=,iv:Ga21JS8gz/Cw8iWGtQQTs7Du3PNDd0YnEkRePjioF8U=,tag:+6eWqu8bL4Bo8vmTbJwFTw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
