apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:CKMHx34sQl03EtEC3yCxRMqU/9kAWvM++4ntAuj/9UHl1PFVMGEkkg==,iv:ZJavlXsrEyronAtrH5/ofyhmo0gHIhv39rgVMTAqmrA=,tag:QZUNAh06etzMwIcEC8WeQw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q8aex20qchscezvgg0ppgcpv0j5mpw9tklr4vakztnktekzscp3q248v2s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaMzZBajZoY3dKbit2VHBn
            NFZrNkxoWGppTlNVQ1pCTGEwQVQ5M0M5L3hvClZhR0UxK0dUS2hjWnNmYlVSaTdq
            S09zcjJwVHpjb2JzeXdLc0xwQ2QzQ0UKLS0tIEkxRk9uVFpSTE1TY3dCOXppMUJ2
            ejQwMlJPeUxtQ2Zqd2g5Sm8rVlIwVjgK1v66gidZunxQFE+/vWtV5UQcNwI8vnxK
            +XiJYD+NRr2rfsMsRyLWi5NtbsbXvYFa+VO+XqgYFsnDvk0yln+hLQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-22T07:52:20Z"
    mac: ENC[AES256_GCM,data:aSYqXVsVU1D+gd3UCcPX2IGwSh3tTRg33qeQ1d1zA+cnGNuWUwQRrkZp8u7NvnPlVu9z9jm8s9+patrex41WscwpuckNts00ZMaGuxD7/VWx9yWToo8NgLAD+Y3dsWTb9rfT6uQAFA18h/u6J9fol2rUyZ3PweYd9Oyl0IGZ+d8=,iv:jON9f1qaem0MJWKsISrYsDydyWiHQTAPSxlFQ/xDE9Q=,tag:W9hWS61Glj2WvBn1i18yag==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
