apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:GvravT/oYTYmnNs=,iv:5vOBWkyC/erSkk/pVosLj7sNXcm5dk5HPlhxyfBAL1w=,tag:zclLyivmrWTgCYiU/T6Wsg==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:B1Ki63N7ZfuA6rBulrErfBM=,iv:KBWo85Hfy37bOBOqV/nJ/goaUZXhN5nZMM90xQ11y1I=,tag:dTTfVjTHe+LQC6phHE2vww==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:ToGwjAg+tEpU5T2eH4ptvUCXap8WokAdXi/sI/GvZuFaiLBI,iv:UuEKRSIA+my3C3QBOj6sd65s19Wv/El2Kl4VgGz7+/g=,tag:2xT330WXnJ052O8mcX3Bpw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q8aex20qchscezvgg0ppgcpv0j5mpw9tklr4vakztnktekzscp3q248v2s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVc2tET3ZrR3Q1Q1FUVzBz
            U2NjNjVSa21oWXRMVjRNcldPbTVBL2tLSnowCjRRYkV4OG01SnhYMUJPb3RvOG1o
            cnM4THA1Yy8wQVE1SlIySTBHWW95RTAKLS0tIFBjUkxDenF4Q29iN0dZZVQvc2xD
            dC9hQTZOT0E0ek1GZ0hqcnF4ZFdmdVkKgAGo6oviOIOlADKKOLCLSKSW6CDAIdme
            4WRgVwlQuxjn26dHCpHMxeGMXfaAWGRsDl4RgCALlwE4sZqGPvRKNg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-25T20:58:57Z"
    mac: ENC[AES256_GCM,data:2R1OBtmtYJpPtHl5uNCbdC2fH1B6dtIz9p+OGud8DOy2eVRML1+O2QJqS5Lpc2GRzCedGLIvl84hp+IRNTgK8Quqcs8Xeyyr9AjpD/YCvZ1q9OJxmpQEARor7nii0pXgVhNaCngJSl7I+G6Y4wMV0nwuHbu92rKS/ZpXKSraFVI=,iv:7xM1zZFw/06Xdi6qZT3XH9mUWUB5VghBc+RKNnrahdA=,tag:1iAVe6HkxDJ44qaq5eXGog==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
