apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:PpL4g1rcZTk2w0o=,iv:NlZ70fwHTzasjMUzPQwEUldpTINaqUHHauIN2fJmPi0=,tag:1v+7UR4R4XHEIZsb4HEgyQ==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:huVHxqFzegYRguXcvvjZU+4=,iv:c3Rc2TQphKEur77K8vNsmWBS45C6QrN4IlfjNz4rJ8Y=,tag:9ojf3+sZ2nJ+RgEqqqwfPw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:MyQmBGXzPLeHYHfiQ3vp6RxgQNrGijvG7Grx5VmuMwGkmkfk,iv:hP4OkwgFECm9qMmru3/6iKRLY8xqH/DSSWtT8UOtaaE=,tag:Rrl5WHfRSn1P6xAUzHi0pA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q8aex20qchscezvgg0ppgcpv0j5mpw9tklr4vakztnktekzscp3q248v2s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzMVJSSFpqR3pQZXd6d1JB
            LzJaN3c2dVoxMExobHZMbXdVZTRySDY1dVE4Cno1TGdjVUQvcVY4NGhuQjJIQTV1
            NS8wNFZvdy9KeFhUQmtMeVZkc04vK1EKLS0tIDhNV1ZpUjJsRXcrV2xGeFhsWDl0
            OUR0U3k5RXFJVW82Njg4KzJ5ZWpmbWsKQyECox8SVuDDyuID8XUkZa+RRBGq24I+
            Dap3q6Tzn3MK35u58NBcx86beo5If5LAHFbqki2q1/cIA0Q8N4heCQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-26T16:39:44Z"
    mac: ENC[AES256_GCM,data:sFdnnLogj29P2zBsbOcMDru/HEpRwVxsBUQsQ0cvLaaKOZpCKGM9KsS7rWaFWm+SvT0DhFtwXFYN1a6f5YL142fd/Kj4ILvqOI4pbXuSxAe7yAteISD6ZG6p1VQL+RvoBZdDzzFtVilUHNBHlr8u1BCGqDISTZlpvHnXybl242o=,iv:79p+Jimlncwwp8l6F3dlF/p3ELbEcrkEx6Jrg48cMGw=,tag:g188w3VLUmK4rx1qJByI7A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
