apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:wtK2jsQoXoKsNDo=,iv:Ccji+6XrV0wJ1Tc5/j4gHg41VIFYQv4XBFYGyZaSRN8=,tag:mIGtQ3Cnw9+pSDYH4/0YPg==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:LED8iiAZHGPGr+0hToxT/Vc=,iv:QpQIADXC0nV13sAj52Y/MgyGdPMMkrynz/cI7BpM+mU=,tag:3mrbTxdWktI9loyhcuNWPQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:mNlmEaorUCVYFyPccMe19i7nPhnKZrXm5RxAm27Q5RlxCEBa,iv:4SXshLAdPGG+EYzB+5/hNIuy3obU4CInFJjDDF9/ACs=,tag:u6i7QFwZXVZGW+wCl7kbjQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q8aex20qchscezvgg0ppgcpv0j5mpw9tklr4vakztnktekzscp3q248v2s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0NWZWam9Yb2E4Q2owRGpT
            WEV2aG1ZZXk1UHJRL1ZQcVVIb2RJcWpNVGdJCjNhZ3huQVNBQkNmQkZSNzBxQUI5
            YUdKTGZBRW93UWFvQ0xGVDlvTkpZSDgKLS0tIHAzVFV0M3p2cmlOZ3M5Qk1xd0M5
            cy82VkVGRzlUdWJKeGpGM0IwTG43ZWcKqVQpe3NXRHAIoQHojvrv4K1pPnXySJff
            ja3HRsamo6VD5qNsd1wGR8HnT6tXKD4lsrajvUZBw6MVkZVYgTk2jQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-25T14:05:29Z"
    mac: ENC[AES256_GCM,data:n+iDDwpyRmhIrhQS6RWnhgpSPdz9f18iLgX4QkzUiciIE8gprXDdnoG3WBlPO0GMixlBa4g3PaGCl2bUsBEx7LnQ7TpnAEay+SGUMmvmE37/IhlvciaIM8J7/FfbRYsp0AhxliMvQ81zlUZLkWahLq22PGtc7PVRiQl2yXChpuk=,iv:pfj5eMnG0kPUSxrYon5YBBHVVOim701DyqKKFhBclZY=,tag:rcxeu5pKEiskeiV2hkmdLw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
