apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:AvkSb4akWj3GWJo=,iv:ZsWedTtpLyd/PaQhVLPGlBAVLXWjUthYrJ4YrsvrCCk=,tag:rMvAlRFVONWRK+uWnyMy3w==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:UHm1SBLjyJLV9i2oTKTEhgs=,iv:ogHloJPxNnttaE+tTNbpXjUJzaaEyBXhU+1qa1nSoNw=,tag:T/RzAFR0v4FB+2crxhE+0w==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:CfLeFIGAvVOX/k+wFJzyli+HEIqmfwKkgTIh/shkEE3/K6fK,iv:zHdE/GIhi2luI5fIx2Jau6pBl0+UYsZmGQL5WmxLoeo=,tag:f6AS4enTdaoqhaPZlu5dHA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q8aex20qchscezvgg0ppgcpv0j5mpw9tklr4vakztnktekzscp3q248v2s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjTmM4R0VsS3VUNTBDKy9E
            SFVkcy9Ra2ZKL2xhckYwWGlPQnpoaGE3MEVzCjBQVFBmbGQyZWJFNGcwL2ZMU1ZS
            RjhMRFRQWjFua05qNUhTejJnK2luR3MKLS0tIGZNWjJMY3drcmM5aCthL3NMdHc1
            OEt5cnhLaFE3aEFZZ1FQUzJ6VVpKclEKc8ZpsOmkY9TF+8sNI6Hwh9ovO6SiLENs
            BQLtuyq6nI86/xMPuxF9bm5fHMBRBvgHb+guF6iaV0yJfcHo5qPS6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-22T07:52:19Z"
    mac: ENC[AES256_GCM,data:WaFKMfD9rXHd6HuKddw/30hnVWFTnOlozLLF1o8tDhCiqp9inVwCnDPDhfrNn/lsDNLePoQ66lEjT2Vfkg4NaHx0n6k1XwSaM037VnJREjscrlEL7+ljQFNODLwImdhSoIHnj9P8qjwDYU4i1Dy8pxUOE14b2feUnyGJM4hTOoM=,iv:+lRexMEUMWF4nhF7Z3gOuIc/X4GJXfbCNu6xunvlcVM=,tag:F5T5E/q3tqoVaTQso0exLw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
