apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:EPxzL6jIJqxu5CM=,iv:N4YFPfjqiX5DYSwFKQoODytlpOafzafC0PVqabQluo4=,tag:YbpfHT9EBBiN62M27imkCA==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:QSTZbyEX1kogBi44qa8JJzE=,iv:mZ0xOxsfioxSg8cpSwZbPeEy38FBj8zrdXtRs+ooDeA=,tag:9qzACaFRkYFxg93frIv0Ow==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:wON0NB+EUiXfn7w6NB+uPT7RsbU4ZU6zvneF5cWOrO1JEVOq,iv:Lbz5Gv2zCNIPPQaIo1JY03+XiDi2Uve+g+gFtJDw9qA=,tag:YbMgK5ur1qe8sDCWxYDg8w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q8aex20qchscezvgg0ppgcpv0j5mpw9tklr4vakztnktekzscp3q248v2s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmMGhQWkk3SC8vQ0lNRFlO
            bUdobExTN2ZqZXR4R25qVTVlQVhrUEl1d1hVCkZJVFRPTWU2TFdTdSt4T3Bsek9Z
            YjEwdVlSVEZtU1RaNlVyQzArWlo4L0UKLS0tIHp0S2QwR2dPMjM0UkVybnZoUkRl
            Zm8rb3A2eGlGUDQ5NjNGU3hqR1E4VTAKPY2q9uMqkncXkgGMfu9AxQnfdbGx/hjE
            lxJ4KOjNGMUjgl87g1AvF/jlWEJaUtT7E8jm9IUrdZD4Pxrgn0wtkw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-24T16:08:03Z"
    mac: ENC[AES256_GCM,data:+JLL3jw64UcOgQk/XNGB5LMOUfE5RN+yExj7poHM5ARHVDHCj3qR/mG5gsWXGMDreDrJYEtdhQ7Fa518PlsQCEoP526wFVtb6Syvw5f0hW2bs4NwKtO9Im4KW5CnBNNQVdVL+KnBAP2QdfXqM8B94EBrM7xYaY3kJqmt6DOxx7Y=,iv:FiBXLbxYOc+zSabgT2ViNiP1vFqSx7VfFB0Ita4HvoE=,tag:me/AIIG/Is/MJEnf5k+lwQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
