apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:bVjouwKf6BCkhAI=,iv:iBjv34G56fQdPvK1bjPHt6w6lQNlpNiaJx/UtUkTQCs=,tag:GSmHGzZyUYTX0cgsAFHO/A==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:9+FQnZ4gyXfoOKbq5cDkK94=,iv:RQaxnRUKUl8p5SSHhtJbUVXeTuMVPqsUgNRnNNVxPaA=,tag:9n+TazfqEif3UYqCkFjRZw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:ADg4FG5zFqYVGuE5OM5XClVG6ZMfQh45ko/5QFWNI7P1y2zM,iv:/S0P7gUq6KckoNMtH95r2IOLXqPV2ieuv9Mmnf9MUFU=,tag:2i8z/sSgFLhac5VriUgoAQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q8aex20qchscezvgg0ppgcpv0j5mpw9tklr4vakztnktekzscp3q248v2s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0VDl1dzdNZzBJT0hwamVw
            MFYrOE9xdEZsSDN2cXVHaVNvZkF2WjJPVDFVCmYyZkRpNmFYbGRVNGZ0NWVzZkJD
            UkIyNzM3TkM1QXRZZ0pNNEVzMEdIVGsKLS0tIEdnd2xoYnlzaGh1Sm52UVN6R0RF
            dlYxaDdmKy9FN0o2dUkvSVNlNExYSG8KwJ4hUt5lR2N2XG9Ida43Z892/Mwu7/1G
            tFn0xJoiE9aazVtBQxpT6GbRWM8XA7rbtm257Ks6xiZwFsWg5Q8ZNA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-28T11:55:45Z"
    mac: ENC[AES256_GCM,data:Rt7yQzbh2l8et+HTLTdpRjjxYheM2gEvchQGFXTIFnvVdVYmhJUNulZ/UlCoyhWMOC0FIcZMrwRv2MmdIyjph7ioOoySTRytXG1UMpjSURZp/6rooSvoTRtVScpiz0p9tCr4vKORKCmSP5zAktcS2r+Xa7sYSW1DtAIX6Ejz17E=,iv:I8YJ41wRYbpq8RwPkgpqxW9mu5sARcXmlZyOlLHGTvI=,tag:eEX1mqi+dTxNFoklnXEj+w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
