---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: rook-ceph
spec:
  interval: 30m
  chart:
    spec:
      chart: rook-ceph
      version: 1.15.x
      sourceRef:
        kind: HelmRepository
        name: rook-release
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    ndm:
      enabled: false
    controllers:
      rook-ceph:
        containers:
          securityContext:
            allowPrivilegeEscalation: true
  releaseName: rook-ceph
  valuesFrom:
  - kind: ConfigMap
    name: rook-ceph-helm-chart-value-overrides
    valuesKey: values.yaml
