apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb-cluster
spec:
  rootPasswordSecretKeyRef:
    name: mariadb-secrets
    key: root_password
    generate: true

  username: mariadb
  passwordSecretKeyRef:
    name: mariadb-secrets
    key: user_password
    generate: true
  database: mariadb

  storage:
    size: 1Gi
    storageClassName: openebs-hostpath

  replicas: 3

  galera:
    enabled: true
    config:
      reuseStorageVolume: true

  myCnf: |
    [mariadb]
    bind-address=*
    default_storage_engine=InnoDB
    binlog_format=row
    innodb_autoinc_lock_mode=2
    innodb_buffer_pool_size=1024M
    max_allowed_packet=256M

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      memory: 1Gi

  livenessProbe:
    initialDelaySeconds: 20
    periodSeconds: 10
    timeoutSeconds: 10

  readinessProbe:
    initialDelaySeconds: 20
    periodSeconds: 10
    timeoutSeconds: 10

  metrics:
    enabled: true

  updateStrategy:
    type: RollingUpdate
