apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: user
spec:
  mariaDbRef:
    name: mariadb

  passwordSecretKeyRef:
    name: mariadb-secrets
    key: user_password
  maxUserConnections: 20
