apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rook-ceph-cluster
  namespace: rook-ceph-system
spec:
  chart:
    spec:
      chart: rook-ceph-cluster
      version: 1.15.x
      sourceRef:
        kind: HelmRepository
        name: rook-release
        namespace: flux-system
  interval: 30m
  timeout: 10m
  install:
    remediation:
      retries: 3
  dependsOn:
    - name: rook-ceph
      namespace: rook-ceph-system
  upgrade:
    remediation:
      retries: -1 # keep trying to remediate
    crds: CreateReplace # Upgrade CRDs on package update
  releaseName: rook-ceph-cluster
  valuesFrom:
    - kind: ConfigMap
      name: rook-ceph-cluster-helm-chart-value-overrides
      valuesKey: values.yaml
