apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:UeExCFWhiC6h+BJnDcMezkIwja/bd9/7c2rDvgAQr/s=,iv:w1zJuZkjCXa9sxiwNjnsbHYzIERJnutWo7zSN1gx8sc=,tag:L8gkXCVJglaMUBnEyO2NMQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q8aex20qchscezvgg0ppgcpv0j5mpw9tklr4vakztnktekzscp3q248v2s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWMHV1UGtjTjlCdFhvaU12
            U2p2WjM1UjdVUlMvRDlmc2wzKzl5Z3dNa0NnClI3QmpTNGlxMGNZekJBU1lSb1dv
            RzlWMFQxWVM1ZE5iWWJhSTNBOHV6clEKLS0tIHpFWTJOWG12OGJ1LzFCMWdhY05W
            bDlDaHdTNVdLSG1INE1GOTQ2SDhpUjQKHViBlCszhA1CPDbDympz+joFHoU3Qq4N
            OfVSFG/K6c3OSJ8uIcoXUdqMcdSIjl45wCzUPEPJE/8FoABM+ai/Ng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-24T15:19:20Z"
    mac: ENC[AES256_GCM,data:KQGtT9spq9x0vpQo3tZflVHIUMNiXw/eOBzG95pwLirlY4nj82s+OwaOS6gAtN9HWnW+WBKASlsAnHnF04WWBOAxr/omR4RUpRm0+df1YwL5mqoDIeiMzHGpVBGbNfDBqN90TU0yRMeXXynnRNY+iBR6wHAa7D0mFa4otBXj+BQ=,iv:LD9nrStP84VoU+2nL49eDbOOK9e4KC9XmRJQR4nJHD8=,tag:fYFQc1zFePTtlV9ZhDDHwA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
