apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:RwvD/sQV+jKUuBCmJJzuH+TG0731vtptfLMHIfNuWRw=,iv:BeU+WNTdILQqA3S9hkXBUDqzj/xErXzkcyIobc1AGwI=,tag:yxTJtDeYKqyIMf3gG5iVDA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q8aex20qchscezvgg0ppgcpv0j5mpw9tklr4vakztnktekzscp3q248v2s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHLzdPdmtHdVZXengzaHk3
            MlRjdVZCaTBmUi9BTDA5ZUpCN1Y5OWpYYUJVCkR6YUJld3BiVlBOWHNuMElYT3la
            TjBPaHIvWmRPbnF2NVp5bm1veThBWXMKLS0tIHFmTFdxaE9WMENHUjBLVVhHOGRi
            MDdCZ05nNHJhbHlnOEcvck0rYklOdk0K7SsfIt38zCoPkDYpely5wzZNXU3JJaPP
            KS/+HPnQuFWEVpJP3SNL93AMMe3jqvVobk3oH8Mye7g2xAcGcrt/VQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-20T10:09:20Z"
    mac: ENC[AES256_GCM,data:PDZodJqwTEhM/2bDHmJTxaZ7sTxUoP9FBP/KlcDi59mHWWaZNk0Ttj++GSkenrDQpFM0TTJNu9hpwOCdNB1aeaZA9LoY8X/Tg7sRSIveMnM7vtxQPcx6OL9cUowKXGNT14Z0adcCyqLLPKNfkvgaA0T6XTjGtaIDo/6eDs8T0Ig=,iv:Dwyo26kcGyIHHW9s7nHDw80ht/g8HB7dLVZkfwI9xcs=,tag:WmBz7ss8SyjxKAXjcpPBpQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
