apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:F/IZNy85dDh8+7vocCoIUZQnUK8YMQdJ0HUNf44jt4M=,iv:VFMzkacPhXfI4xgNDFyw6yGASWgtA0PMM255QweT9No=,tag:Bm3EY2zyePx48UUo5di6EA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q8aex20qchscezvgg0ppgcpv0j5mpw9tklr4vakztnktekzscp3q248v2s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXSXFna1NNdXJtZzdyTk9O
            ZjFrcVZ5N000Z3B6MFlZS3IzV016UldOTlJrClUwMGdzTlVUdTZ6aGVwMi9oMUk5
            M3dBWUVFQkk1d3gwTnRzZStFNHkzZDAKLS0tIGhtUm1aNlFpQUpxeitPa0xnMzVZ
            ZUFsUDZ2Nmh4c1IzMHYrdVZoRmZLa0EKGnGclSyeUm9QL8OSRrHCPJTb2owlvQdN
            tS+1Td29S+ZkAyydqO4+ACWrVLXt0LE3jv1F94YLvw8UuDeSsT99mA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-18T06:13:32Z"
    mac: ENC[AES256_GCM,data:kcomP04+PIjJVrnvx9Cy7FgcF9HwJGE9rc0BGjwvTKXI40f4tiWi0Ss/FJtsaVFpdR2BTqjPxVP6Zq4WNr95P0iyvPTb0YEuQ1H3KK6trmPLeCV+KxisRfLU3rWeuWRg7IdXs8H1wnjP3RaPjDS7Nj1gA3Yg63qX5Nsc7An3U3Y=,iv:m3PbpcDBhA83ikIMUIRuM089sfUltU7BaTbv8WpIueY=,tag:QCkUv4+sYVBhI3j+i3bqpQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
