apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:jpfO3MMP4jS6+0+5hMKZ6uH/OIKFdZCh2S/T6k3ZS3g=,iv:wNhOX5iO7AZ3z8REFHtZrrufmeXGZZMzLLLo5giTrcg=,tag:HMS3sZCo4pEH7nfanODouA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q8aex20qchscezvgg0ppgcpv0j5mpw9tklr4vakztnktekzscp3q248v2s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwb3BMSk93M2RXRHFkQU9F
            Uml2U1dJelFmSGFLZitHRk80MDhWS3BPbWhRCk82MVRSVmQ3UW9yNS96dkdzVGpF
            eFJWMnNGemlvWDRXSWtiTlIxMjBBdE0KLS0tIGdpdGVKbmhjUE5WaXpEQXNkZ3g0
            a0QycDlYcWtSdFlOelpwaWxDSTIrSUUK6sCPXf/Nz8nk1+fpe1a3ucPprT1pLL/A
            Wpwt3xrk4UlGBLOGiXew+R0Jhbi01TxQ9CrnHIQ4OdsMzG9x2TSv1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-26T13:29:55Z"
    mac: ENC[AES256_GCM,data:YFpGHUzv4zczK7oLndBxcboYjeFYn8GNSgmmSWQ8eBDXbtTmRsBRu52JV5gE4EnzfuZlGk27ANOLcW1rsuJnCts/S4PYEz/zYuNphr4VVGfgJas2jdnk4dSvr+iSbWunvuGXOOspA5t2kxF/FRWiOJ8T5Sq7H2lYCoQ0b/yTbNQ=,iv:CbcYZ5Sym6/5FUStRr24j/CJMnjTffKEkmbV/wAaIyY=,tag:7V76fllDcxWaLCVzXF/I/w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
