apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:h7BR81xkgO9KMVCFNOC/887aO80svNnFoPt0DseWxKY=,iv:7ZZA8SIgLIIm9VSz77/BE13XFmvF5gV0zsCNei9HOrU=,tag:Fd3jdxilP0kxO2YkzXemPw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q8aex20qchscezvgg0ppgcpv0j5mpw9tklr4vakztnktekzscp3q248v2s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLMHFUdTNVQmVkZS9CUnNo
            cW1YYkovWXI2ZkczV0JxZG5jNmtjYUg4bVNVCkxOWDd3dysvNnVaZDR2bUlYMysr
            TGNlM01hdm5aVUk0YTNOQTI0cE1OTFUKLS0tIFRYSmZMbEJCV21hc0ZPMkkxOUcr
            MEdWVzhEUUtWbjJKQ2RHYlpqQ1k4TEEKpyI1EqDeHqzzwuak/JJai+BOUCpV6i9N
            fyBL306gr8zcc9CDsgT8HKcb2vYMYkXtkQZa6msW42H9UAUy+N/4ag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-19T14:12:45Z"
    mac: ENC[AES256_GCM,data:axW4fu80r7yFD6yT9tFi3iXeqZqKCqjPJRV0yxF2kIRGEjpAURuTc0Z714EUKh1/r8xI1+s0Xj/ftYOEXxXM8VAu6eA22OisRZ/HUrXUALQu84l/hNcch4CZ4HmyK2uGbUb/geDo/h42L8E2JaQKy6hATgkzdQToUEN4CHEo8OY=,iv:+LjHDbXqkGF0BVph7Jz1TNnXhF4fTmcC1uSVqer1T2U=,tag:Zspunqssv2+KHpPuvJaScw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
