apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:eAatDU7t2Ddhh0wmczbcS6kKZDIXX3oIRepAxU5KxZQ=,iv:/CMKM+hgIJC22ZSxPiO7qXaSJ/XjWrNu4HVdp0HuyIY=,tag:CE9JyANdSkHj6ikDx9XX+Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q8aex20qchscezvgg0ppgcpv0j5mpw9tklr4vakztnktekzscp3q248v2s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSTE41RjQwdVYrZktoQXNW
            QlZrWWpLbzBjSXBFcDd6VytLZXloUU0zUEJJCk5XZk92R2NkWWRPT1JDZFpCQ3Nk
            c1BnUHgwVVU4dExsYXErVHF4ai9GdTAKLS0tIGp2dkZwaTBkMFhoUjJENFg2akw4
            UzNCY05Fcis5OVZZZS8zc3BjQXkwRkkKoIQ6G/fjmVvkz0dchZbuIw4o+q1YXN2Q
            bRnlMoLBRmV+BrfEods7WgAlzgScDmYztYC42y/GJMoXpxd6275rRA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-19T01:54:05Z"
    mac: ENC[AES256_GCM,data:LxChVtiQaOWG1+Ev2/sqpopcUUlGP3tWWcqntwtks6FeQbaHb/gm4nBgwQNEQZFZo+BLNmFfbw3VkSJwFUhluEd0ThL4D2gZGdiiDOqtvl+IO53yV1NwdQsGzkz1scExfHCTKEqffUtNu5eYYoeyUK0ZjL2aDnlEajlXzOEKLT8=,iv:aYXtVfHiVgnnVSeF0yei5nigJVFB7Q5fJqltxcGPLsA=,tag:pCeCgfL2n6JbZMTsWS7lNg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
