---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgres
spec:
  interval: 30m
  chart:
    spec:
      chart: cluster
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: cnpg
        namespace: flux-system
  install:
    remediation:
      retries: 3
  dependsOn:
    name: cloudnative-pg
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: postgres-helm-values
  values:

