apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:MgJjegKfYBkKuFcqeCEXH/aJL/OrOJ4BCX0zSMKKJsuszUsMgT22vA==,iv:/dGOG/rzrYiaLV6LwEitDh/SRsw2p4XXIQNy9/ZDLSc=,tag:renFuGvknzZMaZDMNoNqRQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q8aex20qchscezvgg0ppgcpv0j5mpw9tklr4vakztnktekzscp3q248v2s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxVFBHS1I1NlNGWnovYWhh
            aUkxcTNDVGtEeTFTMndBSGJhaXQvQ3MzYlVFCjh3M0ZvZjdvM1BReHU2bEU4VWc0
            ZWJoWlZ1VDlZd3RuWGdWVThCNTYvWWMKLS0tIFVSWUZ3Q0I1MXlXV3dBUFA4YVdm
            NWlZYnd1ZURqOGsvajhnMHR2K3hGMFkKTWUTR+ZdDUvO2paG+MryMZG4fdSdxuxr
            Bswr9R8ROnD4OyapfvYMvbId/W/H0AEEO/OWLMEjFwOrCHwUalC7xQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-18T15:49:31Z"
    mac: ENC[AES256_GCM,data:E7CgIKMJQc0DaCd2dvg/GcTbAyBOaxbQl6S0GmP5pCEhcJdkhLIem9QE5hBvEb3GDbAwLFTkn4QZ+L+2StDbuFcXNc2hFda+wqb2FF/QVBhS9q88xDyK6j4AijMJ8s9HmBtlomWquoGr0npKC64cDLDVOwLvYwvVpbkb+Eraawc=,iv:UYghQXzXS/qjoAHUnO6y+9ixuW++U5xN05kAVZWx3FY=,tag:j42qb3jlnhNQDClqOPVtBA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
