apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:xLBIXmNFHP6stqI6b3DIECdSDnyfARGMM30OoE8uGUUVEqKmPE8mUA==,iv:Bh76O8UrlI554buGW6hNLWLByID+MWLEnu+tvTshVyo=,tag:BagR8BFZfo7JhOC27SymnA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q8aex20qchscezvgg0ppgcpv0j5mpw9tklr4vakztnktekzscp3q248v2s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwR1o0N21HUDlscXNlTklL
            UDA5WkhzUWQrRWNGdExHOVN1bTgvZTdvWGxFCmkram1adk1hbkpRa1lKVmk4SzhI
            aXBKSjlTRVFpNjZ6aWxYWXRxKy9EUWcKLS0tIGlGakJydEJrSC8vMVNSMlU2YXIy
            eHVTUHl3ZTU2RGp1T0plTFp6R2cxQzAKdFT1D4griyYNKEfYaHZs03ptCnhmUmQo
            Rn6nXj1URFSge5zC/AbkiQvEl1XVnbCoc16K7AbY5YUAkBXKIna4rg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-19T11:12:49Z"
    mac: ENC[AES256_GCM,data:zAZ9JzEhgFmcSmvFasdL72N5xOSYCoJsjQjCYM6Ih3QxSRykVV4RJZVNA4VF6XWA5pTiJCWDh0rj+5g/Q0Edr8vlLSj2puMyJ3vMiNwfDR0UMJYFd0dDRpjYMqLTm/wrWRg5n7T1RRQCgSg9bF6+FirJlv7Xly9tDtp6zU4GdzA=,iv:pWnMz+DkIfsK5lUPHzk/X8sU4bH5XcttDAI8B3x/5TU=,tag:uV+InAGwbKCOQ/sEDSBfYw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
