apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:B2oTQPIooJ4N26UPKk+2FqvZOVaj4+RZAA7m5Utt1X9zOA0/j1kzNQ==,iv:RocJwEHoqQm8HXjGI1WqAC4/hOWwnBpP3QdZvgzQZnM=,tag:ct4aMqvsujMG82tmTJMCrg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q8aex20qchscezvgg0ppgcpv0j5mpw9tklr4vakztnktekzscp3q248v2s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5YkZGeVJGeUV5clJwa1lP
            bUhTejZwYjAwdDZBVlRRTWtoQXF6QXBEc1dvCmxjSDM2VFVvSHhCeHloTUN2TFg5
            Yk1vU1luMUlkdzl0VVNwZTNyN0prTjgKLS0tIGplS3F1T1RkaHp0dkFPVmVPeHZk
            dVBDVnFkWW4xM0g0L2xJRkJFSzBZd1EKLkc4AzHl+wTjqG1HgZdyRlqCV4Mtwo4D
            UR95cs+CMl8A2croUzntVCXrKLug+DHaLq+l5/ixkChL36YYQqI+ow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-24T15:19:21Z"
    mac: ENC[AES256_GCM,data:Ngm9WZvu++fEOlGfDNsM8LA1vFMzUyS0e0HYwawlK0bnrFJfCqQLBKNMHzAgza62ZetCc8tpHq6md14nQYH3e4oVZdChS7oq7CdQD4hyMBXGIdb8iHXIAPTnK67iHxJCEbo3A3vYDbQFLu5Sj1gTS71cSQrcQMbCIqUqcwUdU3s=,iv:L3NAFBqZeYpYa49y2gnG/OvSmnzyrb1gXqD1kz1owyw=,tag:Nmr3iymEiOuFGA3InKbIYQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
