apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:CE4Rp6er1CCrNvQSDM4Fpq2PIrOBvRhZoq0N18bIRIFYD0q1Fqlucg==,iv:Bh/Js7xsBYW+dDXUwBLtqBjzjqNxxTfWt62eU73FI0I=,tag:KTVvye5XVGvkgKp7xn/8bw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q8aex20qchscezvgg0ppgcpv0j5mpw9tklr4vakztnktekzscp3q248v2s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2TC9xR2g3WGNMeS9aL1RR
            MGdEWUhDN0xOaVV0ZFcrREl3blBuN3V5V1RRCjRXOUxzdC9Idy9acWFKekdVV2hS
            YnpDOFVWcTlzUWxLMkxxOVplU2xqMXMKLS0tIFhQTEhDcVBQbXRjYW1TSG1sSktD
            U082MDZzc2QrQ1JlZ1hhRjB0cTlJQ0UKg7WbHG3KCl6v/vuSyojESIIhY5n3oZr+
            00j7Wk3SCI4jp5I/A2XdhO0YVev0QsLQTs4CBHY87UfegCyiDX8dSw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-18T02:58:46Z"
    mac: ENC[AES256_GCM,data:c4+Y+R1CvsUsBsvlrfD1gekp69fn0Lg5doMaaDdVcPaVF/lDQYpGOH4HvFWF8fjBFdLBN+NnsOxbxzrEkHalL5eOVFpzWhysxorGv4SB12ViRWfRiNOlKA5rtL5NXsYOKM5qjA0dxlV3TMRUk5EUIXq1HIOpeVNaISGfZRuspC8=,iv:oMcMf1ZWVmpBnSjdDDAC9Qki4KFweocUzGoRbYcgosg=,tag:Z2nfDAtnHpVzn4vFFFhaWw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
